/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminMessage {
  'id' : bigint,
  'subject' : string,
  'body' : string,
  'isRead' : boolean,
  'toName' : string,
  'timestamp' : bigint,
  'toMobile' : string,
}
export interface Customer {
  'id' : bigint,
  'visitCount' : bigint,
  'name' : string,
  'firstVisit' : bigint,
  'lastVisit' : bigint,
  'mobile' : string,
}
export type ExternalBlob = Uint8Array;
export interface Photo {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'blob' : ExternalBlob,
  'fileType' : string,
  'timestamp' : bigint,
}
export interface PromoSettings {
  'discountCode' : string,
  'offerDescription' : string,
  'discountPercent' : string,
  'isActive' : boolean,
  'offerTitle' : string,
}
export interface Quote {
  'id' : bigint,
  'service' : ServiceType,
  'attachmentUrl' : [] | [string],
  'status' : QuoteStatus,
  'name' : string,
  'statusReason' : [] | [string],
  'timestamp' : bigint,
  'details' : string,
  'mobile' : string,
}
export type QuoteStatus = { 'new' : null } |
  { 'replied' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Review {
  'id' : bigint,
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export type ServiceType = { 'flexBanner' : null } |
  { 'digitalPrinting' : null } |
  { 'tShirtPrinting' : null } |
  { 'stickerPrinting' : null };
export interface SiteSettings {
  'tagline' : string,
  'whatsapp' : string,
  'email' : string,
  'siteName' : string,
  'logoUrl' : string,
  'address' : string,
  'phone' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPhoto' : ActorMethod<[ExternalBlob, string, bigint, string], bigint>,
  'deleteAdminMessage' : ActorMethod<[bigint], boolean>,
  'deletePhoto' : ActorMethod<[bigint], boolean>,
  'deleteReview' : ActorMethod<[bigint], boolean>,
  'getAllAdminMessages' : ActorMethod<[], Array<AdminMessage>>,
  'getAllFiles' : ActorMethod<[], Array<Photo>>,
  'getCustomerByMobile' : ActorMethod<[string], Customer>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getMessagesForCustomer' : ActorMethod<[string], Array<AdminMessage>>,
  'getPhotos' : ActorMethod<[], Array<Photo>>,
  'getPromoSettings' : ActorMethod<[], PromoSettings>,
  'getQuoteById' : ActorMethod<[bigint], Quote>,
  'getQuotes' : ActorMethod<[], Array<Quote>>,
  'getQuotesByMobile' : ActorMethod<[string], Array<Quote>>,
  'getQuotesByService' : ActorMethod<[ServiceType], Array<Quote>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'markMessageRead' : ActorMethod<[bigint], boolean>,
  'registerOrLoginCustomer' : ActorMethod<[string, string], Customer>,
  'sendMessageToCustomer' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'submitQuote' : ActorMethod<
    [string, string, ServiceType, string, [] | [string]],
    bigint
  >,
  'submitReview' : ActorMethod<[string, bigint, string], bigint>,
  'updatePhotoTitle' : ActorMethod<[bigint, string], boolean>,
  'updatePromoSettings' : ActorMethod<[PromoSettings], boolean>,
  'updateQuoteStatus' : ActorMethod<[bigint, QuoteStatus], boolean>,
  'updateQuoteStatusWithReason' : ActorMethod<
    [bigint, QuoteStatus, string],
    boolean
  >,
  'updateSiteSettings' : ActorMethod<[SiteSettings], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];