/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Photo {
    id: bigint;
    title: string;
    order: bigint;
    blob: ExternalBlob;
    fileType: string;
    timestamp: bigint;
}
export interface SiteSettings {
    tagline: string;
    whatsapp: string;
    email: string;
    siteName: string;
    logoUrl: string;
    address: string;
    phone: string;
}
export interface PromoSettings {
    discountCode: string;
    offerDescription: string;
    discountPercent: string;
    isActive: boolean;
    offerTitle: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AdminMessage {
    id: bigint;
    subject: string;
    body: string;
    isRead: boolean;
    toName: string;
    timestamp: bigint;
    toMobile: string;
}
export interface Quote {
    id: bigint;
    service: ServiceType;
    attachmentUrl?: string;
    status: QuoteStatus;
    name: string;
    statusReason?: string;
    timestamp: bigint;
    details: string;
    mobile: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Customer {
    id: bigint;
    visitCount: bigint;
    name: string;
    firstVisit: bigint;
    lastVisit: bigint;
    mobile: string;
}
export interface Review {
    id: bigint;
    name: string;
    message: string;
    timestamp: bigint;
    rating: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum QuoteStatus {
    new_ = "new",
    replied = "replied",
    rejected = "rejected",
    accepted = "accepted"
}
export enum ServiceType {
    flexBanner = "flexBanner",
    digitalPrinting = "digitalPrinting",
    tShirtPrinting = "tShirtPrinting",
    stickerPrinting = "stickerPrinting"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addPhoto(blob: ExternalBlob, title: string, order: bigint, fileType: string): Promise<bigint>;
    deleteAdminMessage(id: bigint): Promise<boolean>;
    deletePhoto(id: bigint): Promise<boolean>;
    deleteReview(id: bigint): Promise<boolean>;
    getAllAdminMessages(): Promise<Array<AdminMessage>>;
    getAllFiles(): Promise<Array<Photo>>;
    getCustomerByMobile(mobile: string): Promise<Customer>;
    getCustomers(): Promise<Array<Customer>>;
    getMessagesForCustomer(mobile: string): Promise<Array<AdminMessage>>;
    getPhotos(): Promise<Array<Photo>>;
    getPromoSettings(): Promise<PromoSettings>;
    getQuoteById(id: bigint): Promise<Quote>;
    getQuotes(): Promise<Array<Quote>>;
    getQuotesByMobile(mobile: string): Promise<Array<Quote>>;
    getQuotesByService(service: ServiceType): Promise<Array<Quote>>;
    getReviews(): Promise<Array<Review>>;
    getSiteSettings(): Promise<SiteSettings>;
    markMessageRead(id: bigint): Promise<boolean>;
    registerOrLoginCustomer(name: string, mobile: string): Promise<Customer>;
    sendMessageToCustomer(toMobile: string, toName: string, subject: string, body: string): Promise<bigint>;
    submitQuote(name: string, mobile: string, service: ServiceType, details: string, attachmentUrl: string | null): Promise<bigint>;
    submitReview(name: string, rating: bigint, message: string): Promise<bigint>;
    updatePhotoTitle(id: bigint, newTitle: string): Promise<boolean>;
    updatePromoSettings(settings: PromoSettings): Promise<boolean>;
    updateQuoteStatus(id: bigint, status: QuoteStatus): Promise<boolean>;
    updateQuoteStatusWithReason(id: bigint, status: QuoteStatus, reason: string): Promise<boolean>;
    updateSiteSettings(settings: SiteSettings): Promise<boolean>;
}
import type { ExternalBlob as _ExternalBlob, Photo as _Photo, Quote as _Quote, QuoteStatus as _QuoteStatus, ServiceType as _ServiceType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addPhoto(arg0: ExternalBlob, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhoto(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhoto(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async deleteAdminMessage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdminMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdminMessage(arg0);
            return result;
        }
    }
    async deletePhoto(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhoto(arg0);
            return result;
        }
    }
    async deleteReview(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async getAllAdminMessages(): Promise<Array<AdminMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdminMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdminMessages();
            return result;
        }
    }
    async getAllFiles(): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFiles();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFiles();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerByMobile(arg0: string): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerByMobile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerByMobile(arg0);
            return result;
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getMessagesForCustomer(arg0: string): Promise<Array<AdminMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesForCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesForCustomer(arg0);
            return result;
        }
    }
    async getPhotos(): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotos();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotos();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPromoSettings(): Promise<PromoSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromoSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromoSettings();
            return result;
        }
    }
    async getQuoteById(arg0: bigint): Promise<Quote> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuoteById(arg0);
                return from_candid_Quote_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuoteById(arg0);
            return from_candid_Quote_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotes(): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotes();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotes();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotesByMobile(arg0: string): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotesByMobile(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotesByMobile(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotesByService(arg0: ServiceType): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotesByService(to_candid_ServiceType_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotesByService(to_candid_ServiceType_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews();
            return result;
        }
    }
    async getSiteSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return result;
        }
    }
    async markMessageRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageRead(arg0);
            return result;
        }
    }
    async registerOrLoginCustomer(arg0: string, arg1: string): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrLoginCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrLoginCustomer(arg0, arg1);
            return result;
        }
    }
    async sendMessageToCustomer(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageToCustomer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageToCustomer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitQuote(arg0: string, arg1: string, arg2: ServiceType, arg3: string, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuote(arg0, arg1, to_candid_ServiceType_n21(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuote(arg0, arg1, to_candid_ServiceType_n21(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async submitReview(arg0: string, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePhotoTitle(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePhotoTitle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePhotoTitle(arg0, arg1);
            return result;
        }
    }
    async updatePromoSettings(arg0: PromoSettings): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePromoSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePromoSettings(arg0);
            return result;
        }
    }
    async updateQuoteStatus(arg0: bigint, arg1: QuoteStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuoteStatus(arg0, to_candid_QuoteStatus_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuoteStatus(arg0, to_candid_QuoteStatus_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateQuoteStatusWithReason(arg0: bigint, arg1: QuoteStatus, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuoteStatusWithReason(arg0, to_candid_QuoteStatus_n24(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuoteStatusWithReason(arg0, to_candid_QuoteStatus_n24(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateSiteSettings(arg0: SiteSettings): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteSettings(arg0);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Photo_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Photo): Promise<Photo> {
    return await from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_QuoteStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteStatus): QuoteStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Quote_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quote): Quote {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    order: bigint;
    blob: _ExternalBlob;
    fileType: string;
    timestamp: bigint;
}): Promise<{
    id: bigint;
    title: string;
    order: bigint;
    blob: ExternalBlob;
    fileType: string;
    timestamp: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        order: value.order,
        blob: await from_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.blob),
        fileType: value.fileType,
        timestamp: value.timestamp
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    service: _ServiceType;
    attachmentUrl: [] | [string];
    status: _QuoteStatus;
    name: string;
    statusReason: [] | [string];
    timestamp: bigint;
    details: string;
    mobile: string;
}): {
    id: bigint;
    service: ServiceType;
    attachmentUrl?: string;
    status: QuoteStatus;
    name: string;
    statusReason?: string;
    timestamp: bigint;
    details: string;
    mobile: string;
} {
    return {
        id: value.id,
        service: from_candid_ServiceType_n15(_uploadFile, _downloadFile, value.service),
        attachmentUrl: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.attachmentUrl)),
        status: from_candid_QuoteStatus_n18(_uploadFile, _downloadFile, value.status),
        name: value.name,
        statusReason: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.statusReason)),
        timestamp: value.timestamp,
        details: value.details,
        mobile: value.mobile
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flexBanner: null;
} | {
    digitalPrinting: null;
} | {
    tShirtPrinting: null;
} | {
    stickerPrinting: null;
}): ServiceType {
    return "flexBanner" in value ? ServiceType.flexBanner : "digitalPrinting" in value ? ServiceType.digitalPrinting : "tShirtPrinting" in value ? ServiceType.tShirtPrinting : "stickerPrinting" in value ? ServiceType.stickerPrinting : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    replied: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): QuoteStatus {
    return "new" in value ? QuoteStatus.new : "replied" in value ? QuoteStatus.replied : "rejected" in value ? QuoteStatus.rejected : "accepted" in value ? QuoteStatus.accepted : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quote>): Array<Quote> {
    return value.map((x)=>from_candid_Quote_n13(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Photo>): Promise<Array<Photo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Photo_n10(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_QuoteStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteStatus): _QuoteStatus {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    flexBanner: null;
} | {
    digitalPrinting: null;
} | {
    tShirtPrinting: null;
} | {
    stickerPrinting: null;
} {
    return value == ServiceType.flexBanner ? {
        flexBanner: null
    } : value == ServiceType.digitalPrinting ? {
        digitalPrinting: null
    } : value == ServiceType.tShirtPrinting ? {
        tShirtPrinting: null
    } : value == ServiceType.stickerPrinting ? {
        stickerPrinting: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteStatus): {
    new: null;
} | {
    replied: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == QuoteStatus.new ? {
        new_: null
    } : value == QuoteStatus.replied ? {
        replied: null
    } : value == QuoteStatus.rejected ? {
        rejected: null
    } : value == QuoteStatus.accepted ? {
        accepted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
